### ISSUE TITLE
Don't force to use mysql, don't reinvent the DBI wheel :)

### ISSUE THREAD

**Issue by asb-capfan** [srchulo/DataTables#1]
In the current code, mysql is hardcoded. Why not just have the user provide a database handle and use a library like SQL::Abstract to build the queries? 
This way, the module can be used with (for example) SQLite as well.
If it's OK for you, I can submit a pull request.

**Comment by srchulo** [comment]
Sure, that sounds great! From looking at SQL::Abstract's documentation though I don't see how it allows SQLite? Does it also allow other databases?

**Comment by asb-capfan** [comment]
Pull request for replacing hard-coded mysql credentials by database handle done. 
As switching to SQL::Abstract is a bit more work, it will come later.

**Comment by asb-capfan** [comment]
It's done. Sorry, it's a lot to review. Could you please test with mysql? Maybe you can even add a test case (e.g. execute only when certain environment variables for database connection are set).

**Comment by srchulo** [comment]
Sorry for the delay-- I've been pretty busy recently. I'll review this soon!
