### ISSUE TITLE
Add query as argument (at least to new)

### ISSUE THREAD

**Issue by asb-capfan** [srchulo/DataTables#10]
I would like to add a possibility to re-use an existing query. Mainly, to make testing easier. This way, one can simply provide a query object with a param method, that will be accessed by the module. 

There is multiple approaches:
* add a param to new
* add a new attribute, like dbh
* create an accessor method similar to cgiapp_get_query of [CGI::Application](http://search.cpan.org/~markstos/CGI-Application-4.50/lib/CGI/Application.pm#cgiapp_get_query()) that can be overridden

Not sure if it could be useful for anything other than testing.

Would it be ok to add this feature and which possibility do you prefer?

**Comment by srchulo** [comment]
I think adding a param to new sounds like the right way to go.
