### ISSUE TITLE
Add DataTable's page at MetaCPAN as GitHub repo website

### ISSUE THREAD

**Issue by asb-capfan** [srchulo/DataTables#15]
It is possible to define a website along with the Github repository name. 
Could you please add a link to https://metacpan.org/pod/DataTables as website to make it easier for noobs to find the module's documentation?

**Comment by srchulo** [comment]
What do you mean define a website?

**Comment by asb-capfan** [comment]
If you open your repository for DataTables on GitHub´and go to the Code tab, you can see an edit icon on the right side near the repositorys name. When clicking edit, you can change the name of your repository as well add a website. 
I propose to set the website to the metacpan url mentioned above.

![sample](https://user-images.githubusercontent.com/131959/30817549-6c65d36a-a219-11e7-90a1-117979dc0500.JPG)

**Comment by srchulo** [comment]
Thanks for the explanation! Done.
