### ISSUE TITLE
replace CGI by CGI::Simple

### ISSUE THREAD

**Issue by asb-capfan** [srchulo/DataTables#2]
As CGI is only used to access query parameters, a more lightweight module like CGI::Simple would be sufficient, too. 
In addition, CGI has been removed from the core, so it doesn't matter if CGI or CGI::Simple has to be installed as dependency.
If you like the idea, I can submit a pull request.

**Comment by srchulo** [comment]
That sounds great! Thank you :)

**Comment by asb-capfan** [comment]
Pull request for replacing CGI::Simple done.
