### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by asb-capfan** [srchulo/DataTables#33]
Could you maybe set up Travis CI for this repository? It's really simple (just create an account and add a .travis.yml file) and it gives you automated tests for pull requests. Cf. https://travis-ci.org

**Comment by srchulo** [comment]
So I have no experience with this. Are Travis CL and docker separate? Or would the tests run in a docker container?

**Comment by asb-capfan** [comment]
Docker and Travis are 2 separate things. I do not know if Travis uses docker, or how they do it. 

The Travis CI application hooks up to GitHub pull request events and allows to run the standard make test command. It then checks for a successful test. You can have a look at the log files.

You can see it here, I enabled it for another dist: https://github.com/asb-capfan/DFA-Simple

All I did was register for an open source Travis CI account, allow top access the repos Pull Request events and add a travis file: https://github.com/asb-capfan/DFA-Simple/blob/master/.travis.yml

Finally, I added this small badge to the readme, to show the build status :)

**Comment by srchulo** [comment]
Okay, I believe I set this up. Can you check if I did it correctly? Then we can close this.

**Comment by asb-capfan** [comment]
I would say it's OK. Thank you!
