### ISSUE TITLE
Please create a new CPAN release

### ISSUE THREAD

**Issue by asb-capfan** [srchulo/DataTables#37]
Could you please release a new version of DataTables to CPAN to publish the changes? 

I would be happy to do co-maint for the module on CPAN if you like, so I could push new releases, too.

**Comment by srchulo** [comment]
@asb-capfan sure! I will add you as a co maintainer. What's your CPAN ID?

**Comment by asb-capfan** [comment]
Thanky! My PAUSE ID is ASB. Maybe you could also add me as a collaborator for this repo then?

**Comment by srchulo** [comment]
I've added you as a co-maintainer in PAUSE and invited you as a collaborator to this repo. Let me know if those work and then we can close!

**Comment by asb-capfan** [comment]
Looks good. Thank you very much :)
