### ISSUE TITLE
Is there a reason for AutoLoader?

### ISSUE THREAD

**Issue by asb-capfan** [srchulo/DataTables#6]
Is there a reason why the module uses AutoLoader? As far as I can see, all methods are preloaded (plz correct me if I'm wrong).

**Comment by srchulo** [comment]
Maybe there was at some point, doesn't look like there is now. Thanks for looking into all of this! I'm at work right now, so I can't fix it. But I could do this later.

**Comment by asb-capfan** [comment]
Fixed, AutoLoader has been removed.
